steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - tb-update-handles
      - --source=.
      - --runtime=python37
      - --entry-point=main
      - --trigger-http
